# Generated by Django 5.2.3 on 2025-07-03 16:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOnHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total en Dólares (USD)')),
                ('total_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total en Bolívares (BS)')),
            ],
            options={
                'verbose_name_plural': 'Efectivo Disponible',
            },
        ),
        migrations.CreateModel(
            name='CashVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo USD (Efectivo)')),
                ('balance_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Bolívares')),
                ('balance_usdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo USDT')),
                ('balance_zelle', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Zelle')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('identifier', models.CharField(max_length=20, unique=True, verbose_name='Cédula o RIF')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador')], default='operator', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('SELL_USD_FOR_BS', 'Venta USD por BS'), ('BUY_USD_FOR_BS', 'Compra USD por BS'), ('USDT_FOR_CASH', 'Doy USDT, Recibo Efectivo (Comisión %)'), ('CASH_FOR_USDT', 'Doy Efectivo, Recibo USDT (Comisión %)'), ('USDT_FOR_BS', 'Doy USDT por Bolívares (Tasa)'), ('ZELLE_FOR_CASH', 'Doy Zelle, Recibo Efectivo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Anulada')], default='pending', max_length=10)),
                ('amount_in', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de Entrada')),
                ('rate_or_fee', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa / Porcentaje (%)')),
                ('amount_out', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Monto de Salida (Calculado)')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='Ganancia (Calculada)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv_transactions', to='exchange.client')),
            ],
        ),
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha de la Jornada')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='closed', max_length=10, verbose_name='Estado')),
                ('opening_balance_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Inicial USD')),
                ('opening_balance_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Inicial BS')),
                ('closing_balance_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final USD')),
                ('closing_balance_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final BS')),
                ('total_usd_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total USD Recibidos')),
                ('total_usd_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total USD Entregados')),
                ('total_bs_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total BS Recibidos')),
                ('total_bs_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total BS Entregados')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('sell_usd', 'Venta de Dólares (Cliente recibe USD, paga con BS)'), ('buy_usd', 'Compra de Dólares (Cliente recibe BS, paga con USD)')], max_length=10, verbose_name='Tipo de Operación')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto en Dólares (USD)')),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tasa de Cambio (BS por $1)')),
                ('amount_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Monto en Bolívares (BS)')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente por Recibir Pago del Cliente'), ('pending_delivery', 'Pendiente por Entregar Dinero al Cliente'), ('completed', 'Completada'), ('cancelled', 'Anulada')], default='pending_payment', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Transacción')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='exchange.client', verbose_name='Cliente')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
        ),
        migrations.CreateModel(
            name='VaultSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de la Jornada')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='closed', max_length=10)),
                ('opening_balance_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_balance_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_balance_usdt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_balance_zelle', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_balance_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_opened_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exchange.cashvault')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('vault', 'date')},
            },
        ),
    ]
