# Generated by Django 5.2.3 on 2025-07-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedtransaction',
            name='amount_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto de Salida (Calculado)'),
        ),
        migrations.AlterField(
            model_name='advancedtransaction',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Ganancia (Calculada)'),
        ),
    ]
