# Generated by Django 5.2.3 on 2025-07-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_clientworksheet_advancedtransaction_worksheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedtransaction',
            name='base_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de referencia para calcular la ganancia en operaciones sin comisión (ej. tasa del BCV).', max_digits=12, null=True, verbose_name='Tasa Base/Costo (Opcional)'),
        ),
        migrations.AlterField(
            model_name='advancedtransaction',
            name='rate_or_fee',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa de Operación / Fee (%)'),
        ),
    ]
