# Generated by Django 5.2.3 on 2025-07-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_remove_advancedtransaction_base_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedtransaction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='advancedtransaction',
            name='operation_type',
            field=models.CharField(choices=[('SELL_USD_FOR_BS', 'Venta USD por BS'), ('BUY_USD_FOR_BS', 'Compra USD por BS'), ('USDT_FOR_CASH', 'Doy USDT, Recibo Efectivo (Comisión %)'), ('CASH_FOR_USDT', 'Doy Efectivo, Recibo USDT (Comisión %)'), ('USDT_FOR_BS', 'Doy USDT por Bolívares (Tasa)'), ('ZELLE_FOR_CASH', 'Doy Zelle, Recibo Efectivo (Comisión %)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='advancedtransaction',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Ganancia Calculada (en BS)'),
        ),
    ]
