# Generated by Django 5.2.3 on 2025-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_advancedtransaction_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedtransaction',
            name='base_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Para operaciones de tasa, introduce tu costo de referencia para calcular la ganancia.', max_digits=12, null=True, verbose_name='Tasa Base/Costo (Opcional)'),
        ),
        migrations.AlterField(
            model_name='advancedtransaction',
            name='amount_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='advancedtransaction',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
