# Generated by Django 5.2.3 on 2025-08-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_improve_profit_calculation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedtransaction',
            options={'ordering': ['-created_at']},
        ),
    ]
