# Generated by Django 5.2.3 on 2025-07-01 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha de la Jornada')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='closed', max_length=10, verbose_name='Estado')),
                ('opening_balance_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Inicial USD')),
                ('opening_balance_bs', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Inicial BS')),
                ('closing_balance_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final USD')),
                ('closing_balance_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final BS')),
                ('total_usd_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total USD Recibidos')),
                ('total_usd_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total USD Entregados')),
                ('total_bs_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total BS Recibidos')),
                ('total_bs_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total BS Entregados')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
