# Generated by Django 5.2.3 on 2025-07-18 16:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='exchange.client')),
            ],
            options={
                'unique_together': {('client', 'date')},
            },
        ),
        migrations.AddField(
            model_name='advancedtransaction',
            name='worksheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='exchange.clientworksheet'),
        ),
        migrations.CreateModel(
            name='VaultAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('injection', 'Inyección de Capital'), ('withdrawal', 'Retiro de Capital'), ('correction', 'Corrección de Saldo')], max_length=20, verbose_name='Tipo de Ajuste')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_usdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_zelle', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reason', models.TextField(verbose_name='Motivo del Ajuste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='exchange.cashvault')),
            ],
        ),
    ]
