# Generated by Django 5.2.3 on 2025-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_advancedtransaction_base_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedtransaction',
            name='base_rate',
        ),
        migrations.AlterField(
            model_name='advancedtransaction',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Ganancia Directa (Comisión)'),
        ),
    ]
