# Generated by Django 5.2.3 on 2025-08-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_alter_advancedtransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedtransaction',
            name='amount_primary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Principal de la Operación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advancedtransaction',
            name='amount_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto que Recibes (Entrada)'),
        ),
        migrations.AlterField(
            model_name='advancedtransaction',
            name='amount_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto que Das (Salida)'),
        ),
    ]
