# Generated by Django 5.2.3 on 2025-08-18 19:04

from django.db import migrations
from decimal import Decimal

def populate_amount_primary(apps, schema_editor):
    AdvancedTransaction = apps.get_model('exchange', 'AdvancedTransaction')
    
    for transaction in AdvancedTransaction.objects.all():
        # Lógica inversa: deducir amount_primary desde amount_in existente
        # Nota: amount_in era el monto que se introducía en el formulario
        
        # En el sistema anterior, amount_in era el monto principal de la operación
        # Por lo que podemos usar amount_in como amount_primary
        transaction.amount_primary = transaction.amount_in
        
        # Solo guardamos sin activar la nueva lógica de cálculo
        transaction.save(update_fields=['amount_primary'])

def reverse_populate_amount_primary(apps, schema_editor):
    # Para reversión, simplemente ponemos amount_primary en 0
    AdvancedTransaction = apps.get_model('exchange', 'AdvancedTransaction')
    AdvancedTransaction.objects.all().update(amount_primary=0)

class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_add_amount_primary_field'),
    ]

    operations = [
        migrations.RunPython(populate_amount_primary, reverse_populate_amount_primary),
    ]
